type country = {
  name: string;
  nameKorea: string;
  icon: string;
};

export const netflixCountry: country[] = [
  { name: "Argentina", nameKorea: "아르헨티나", icon: "🇦🇷" },
  { name: "Australia", nameKorea: "호주", icon: "🇦🇺" },
  { name: "Austria", nameKorea: "오스트리아", icon: "🇦🇹" },
  { name: "Bahamas", nameKorea: "바하마", icon: "🇧🇸" },
  { name: "Bahrain", nameKorea: "바레인", icon: "🇧🇭" },
  { name: "Bangladesh", nameKorea: "방글라데시", icon: "🇧🇩" },
  { name: "Belgium", nameKorea: "벨기에", icon: "🇧🇪" },
  { name: "Bolivia", nameKorea: "볼리비아", icon: "🇧🇴" },
  { name: "Brazil", nameKorea: "브라질", icon: "🇧🇷" },
  { name: "Bulgaria", nameKorea: "불가리아", icon: "🇧🇬" },
  { name: "Canada", nameKorea: "캐나다", icon: "🇨🇦" },
  { name: "Chile", nameKorea: "칠레", icon: "🇨🇱" },
  { name: "Colombia", nameKorea: "콜롬비아", icon: "🇨🇴" },
  { name: "CostaRica", nameKorea: "코스타리카", icon: "🇨🇷" },
  { name: "Croatia", nameKorea: "크로아티아", icon: "🇭🇷" },
  { name: "Cyprus", nameKorea: "키프로스", icon: "🇨🇾" },
  { name: "CzechRepublic", nameKorea: "체코", icon: "🇨🇿" },
  { name: "Denmark", nameKorea: "덴마크", icon: "🇩🇰" },
  { name: "DominicanRepublic", nameKorea: "도미니카 공화국", icon: "🇩🇴" },
  { name: "Ecuador", nameKorea: "에콰도르", icon: "🇪🇨" },
  { name: "Egypt", nameKorea: "이집트", icon: "🇪🇬" },
  { name: "ElSalvador", nameKorea: "엘살바도르", icon: "🇸🇻" },
  { name: "Estonia", nameKorea: "에스토니아", icon: "🇪🇪" },
  { name: "Finland", nameKorea: "핀란드", icon: "🇫🇮" },
  { name: "France", nameKorea: "프랑스", icon: "🇫🇷" },
  { name: "Germany", nameKorea: "독일", icon: "🇩🇪" },
  { name: "Greece", nameKorea: "그리스", icon: "🇬🇷" },
  { name: "Guatemala", nameKorea: "과테말라", icon: "🇬🇹" },
  { name: "Honduras", nameKorea: "온두라스", icon: "🇭🇳" },
  { name: "HongKong", nameKorea: "홍콩", icon: "🇭🇰" },
  { name: "Hungary", nameKorea: "헝가리", icon: "🇭🇺" },
  { name: "Iceland", nameKorea: "아이슬란드", icon: "🇮🇸" },
  { name: "India", nameKorea: "인도", icon: "🇮🇳" },
  { name: "Indonesia", nameKorea: "인도네시아", icon: "🇮🇩" },
  { name: "Israel", nameKorea: "이스라엘", icon: "🇮🇱" },
  { name: "Italy", nameKorea: "이탈리아", icon: "🇮🇹" },
  { name: "Jamaica", nameKorea: "자메이카", icon: "🇯🇲" },
  { name: "Japan", nameKorea: "일본", icon: "🇯🇵" },
  { name: "Jordan", nameKorea: "요르단", icon: "🇯🇴" },
  { name: "Kenya", nameKorea: "케냐", icon: "🇰🇪" },
  { name: "Kuwait", nameKorea: "쿠웨이트", icon: "🇰🇼" },
  { name: "Latvia", nameKorea: "라트비아", icon: "🇱🇻" },
  { name: "Lebanon", nameKorea: "레바논", icon: "🇱🇧" },
  { name: "Lithuania", nameKorea: "리투아니아", icon: "🇱🇹" },
  { name: "Luxembourg", nameKorea: "룩셈부르크", icon: "🇱🇺" },
  { name: "Malaysia", nameKorea: "말레이시아", icon: "🇲🇾" },
  { name: "Maldives", nameKorea: "몰디브", icon: "🇲🇻" },
  { name: "Malta", nameKorea: "몰타", icon: "🇲🇹" },
  { name: "Mauritius", nameKorea: "모리셔스", icon: "🇲🇺" },
  { name: "Mexico", nameKorea: "멕시코", icon: "🇲🇽" },
  { name: "Morocco", nameKorea: "모로코", icon: "🇲🇦" },
  { name: "Netherlands", nameKorea: "네덜란드", icon: "🇳🇱" },
  { name: "NewZealand", nameKorea: "뉴질랜드", icon: "🇳🇿" },
  { name: "Nicaragua", nameKorea: "니카라과", icon: "🇳🇮" },
  { name: "Nigeria", nameKorea: "나이지리아", icon: "🇳🇬" },
  { name: "Norway", nameKorea: "노르웨이", icon: "🇳🇴" },
  { name: "Oman", nameKorea: "오만", icon: "🇴🇲" },
  { name: "Pakistan", nameKorea: "파키스탄", icon: "🇵🇰" },
  { name: "Panama", nameKorea: "파나마", icon: "🇵🇦" },
  { name: "Paraguay", nameKorea: "파라과이", icon: "🇵🇾" },
  { name: "Peru", nameKorea: "페루", icon: "🇵🇪" },
  { name: "Philippines", nameKorea: "필리핀", icon: "🇵🇭" },
  { name: "Poland", nameKorea: "폴란드", icon: "🇵🇱" },
  { name: "Portugal", nameKorea: "포르투갈", icon: "🇵🇹" },
  { name: "Qatar", nameKorea: "카타르", icon: "🇶🇦" },
  { name: "Romania", nameKorea: "루마니아", icon: "🇷🇴" },
  { name: "SaudiArabia", nameKorea: "사우디아라비아", icon: "🇸🇦" },
  { name: "Serbia", nameKorea: "세르비아", icon: "🇷🇸" },
  { name: "Singapore", nameKorea: "싱가포르", icon: "🇸🇬" },
  { name: "Slovakia", nameKorea: "슬로바키아", icon: "🇸🇰" },
  { name: "Slovenia", nameKorea: "슬로베니아", icon: "🇸🇮" },
  { name: "SouthAfrica", nameKorea: "남아프리카 공화국", icon: "🇿🇦" },
  { name: "SouthKorea", nameKorea: "대한민국", icon: "🇰🇷" },
  { name: "Spain", nameKorea: "스페인", icon: "🇪🇸" },
  { name: "SriLanka", nameKorea: "스리랑카", icon: "🇱🇰" },
  { name: "Sweden", nameKorea: "스웨덴", icon: "🇸🇪" },
  { name: "Switzerland", nameKorea: "스위스", icon: "🇨🇭" },
  { name: "Taiwan", nameKorea: "대만", icon: "🇹🇼" },
  { name: "Thailand", nameKorea: "태국", icon: "🇹🇭" },
  { name: "Trinidad", nameKorea: "트리니다드", icon: "🇹🇹" },
  { name: "Turkey", nameKorea: "터키", icon: "🇹🇷" },
  { name: "Ukraine", nameKorea: "우크라이나", icon: "🇺🇦" },
  { name: "UnitedArabEmirates", nameKorea: "아랍에미리트", icon: "🇦🇪" },
  { name: "UnitedKingdom", nameKorea: "영국", icon: "🇬🇧" },
  { name: "UnitedStates", nameKorea: "미국", icon: "🇺🇸" },
  { name: "Uruguay", nameKorea: "우루과이", icon: "🇺🇾" },
  { name: "Venezuela", nameKorea: "베네수엘라", icon: "🇻🇪" },
  { name: "Vietnam", nameKorea: "베트남", icon: "🇻🇳" },
];
