type country = {
  name: string;
  nameKorea: string;
  icon: string;
};

export const netflixCountry: country[] = [
  { name: "argentina", nameKorea: "아르헨티나", icon: "🇦🇷" },
  { name: "australia", nameKorea: "호주", icon: "🇦🇺" },
  { name: "austria", nameKorea: "오스트리아", icon: "🇦🇹" },
  { name: "bahamas", nameKorea: "바하마", icon: "🇧🇸" },
  { name: "bahrain", nameKorea: "바레인", icon: "🇧🇭" },
  { name: "bangladesh", nameKorea: "방글라데시", icon: "🇧🇩" },
  { name: "belgium", nameKorea: "벨기에", icon: "🇧🇪" },
  { name: "bolivia", nameKorea: "볼리비아", icon: "🇧🇴" },
  { name: "brazil", nameKorea: "브라질", icon: "🇧🇷" },
  { name: "bulgaria", nameKorea: "불가리아", icon: "🇧🇬" },
  { name: "canada", nameKorea: "캐나다", icon: "🇨🇦" },
  { name: "chile", nameKorea: "칠레", icon: "🇨🇱" },
  { name: "colombia", nameKorea: "콜롬비아", icon: "🇨🇴" },
  { name: "costa-rica", nameKorea: "코스타리카", icon: "🇨🇷" },
  { name: "croatia", nameKorea: "크로아티아", icon: "🇭🇷" },
  { name: "cyprus", nameKorea: "키프로스", icon: "🇨🇾" },
  { name: "czech-republic", nameKorea: "체코", icon: "🇨🇿" },
  { name: "denmark", nameKorea: "덴마크", icon: "🇩🇰" },
  { name: "dominican-republic", nameKorea: "도미니카 공화국", icon: "🇩🇴" },
  { name: "ecuador", nameKorea: "에콰도르", icon: "🇪🇨" },
  { name: "egypt", nameKorea: "이집트", icon: "🇪🇬" },
  { name: "elSalvador", nameKorea: "엘살바도르", icon: "🇸🇻" },
  { name: "estonia", nameKorea: "에스토니아", icon: "🇪🇪" },
  { name: "finland", nameKorea: "핀란드", icon: "🇫🇮" },
  { name: "france", nameKorea: "프랑스", icon: "🇫🇷" },
  { name: "germany", nameKorea: "독일", icon: "🇩🇪" },
  { name: "greece", nameKorea: "그리스", icon: "🇬🇷" },
  { name: "guatemala", nameKorea: "과테말라", icon: "🇬🇹" },
  { name: "honduras", nameKorea: "온두라스", icon: "🇭🇳" },
  { name: "hong-kong", nameKorea: "홍콩", icon: "🇭🇰" },
  { name: "hungary", nameKorea: "헝가리", icon: "🇭🇺" },
  { name: "iceland", nameKorea: "아이슬란드", icon: "🇮🇸" },
  { name: "india", nameKorea: "인도", icon: "🇮🇳" },
  { name: "indonesia", nameKorea: "인도네시아", icon: "🇮🇩" },
  { name: "israel", nameKorea: "이스라엘", icon: "🇮🇱" },
  { name: "italy", nameKorea: "이탈리아", icon: "🇮🇹" },
  { name: "jamaica", nameKorea: "자메이카", icon: "🇯🇲" },
  { name: "japan", nameKorea: "일본", icon: "🇯🇵" },
  { name: "jordan", nameKorea: "요르단", icon: "🇯🇴" },
  { name: "kenya", nameKorea: "케냐", icon: "🇰🇪" },
  { name: "kuwait", nameKorea: "쿠웨이트", icon: "🇰🇼" },
  { name: "latvia", nameKorea: "라트비아", icon: "🇱🇻" },
  { name: "lebanon", nameKorea: "레바논", icon: "🇱🇧" },
  { name: "lithuania", nameKorea: "리투아니아", icon: "🇱🇹" },
  { name: "luxembourg", nameKorea: "룩셈부르크", icon: "🇱🇺" },
  { name: "malaysia", nameKorea: "말레이시아", icon: "🇲🇾" },
  { name: "maldives", nameKorea: "몰디브", icon: "🇲🇻" },
  { name: "malta", nameKorea: "몰타", icon: "🇲🇹" },
  { name: "mauritius", nameKorea: "모리셔스", icon: "🇲🇺" },
  { name: "mexico", nameKorea: "멕시코", icon: "🇲🇽" },
  { name: "morocco", nameKorea: "모로코", icon: "🇲🇦" },
  { name: "netherlands", nameKorea: "네덜란드", icon: "🇳🇱" },
  { name: "new-zealand", nameKorea: "뉴질랜드", icon: "🇳🇿" },
  { name: "nicaragua", nameKorea: "니카라과", icon: "🇳🇮" },
  { name: "nigeria", nameKorea: "나이지리아", icon: "🇳🇬" },
  { name: "norway", nameKorea: "노르웨이", icon: "🇳🇴" },
  { name: "oman", nameKorea: "오만", icon: "🇴🇲" },
  { name: "pakistan", nameKorea: "파키스탄", icon: "🇵🇰" },
  { name: "panama", nameKorea: "파나마", icon: "🇵🇦" },
  { name: "paraguay", nameKorea: "파라과이", icon: "🇵🇾" },
  { name: "peru", nameKorea: "페루", icon: "🇵🇪" },
  { name: "philippines", nameKorea: "필리핀", icon: "🇵🇭" },
  { name: "poland", nameKorea: "폴란드", icon: "🇵🇱" },
  { name: "portugal", nameKorea: "포르투갈", icon: "🇵🇹" },
  { name: "qatar", nameKorea: "카타르", icon: "🇶🇦" },
  { name: "romania", nameKorea: "루마니아", icon: "🇷🇴" },
  { name: "saudiArabia", nameKorea: "사우디아라비아", icon: "🇸🇦" },
  { name: "serbia", nameKorea: "세르비아", icon: "🇷🇸" },
  { name: "singapore", nameKorea: "싱가포르", icon: "🇸🇬" },
  { name: "slovakia", nameKorea: "슬로바키아", icon: "🇸🇰" },
  { name: "slovenia", nameKorea: "슬로베니아", icon: "🇸🇮" },
  { name: "south-africa", nameKorea: "남아프리카 공화국", icon: "🇿🇦" },
  { name: "south-korea", nameKorea: "대한민국", icon: "🇰🇷" },
  { name: "spain", nameKorea: "스페인", icon: "🇪🇸" },
  { name: "sri-lanka", nameKorea: "스리랑카", icon: "🇱🇰" },
  { name: "sweden", nameKorea: "스웨덴", icon: "🇸🇪" },
  { name: "switzerland", nameKorea: "스위스", icon: "🇨🇭" },
  { name: "taiwan", nameKorea: "대만", icon: "🇹🇼" },
  { name: "thailand", nameKorea: "태국", icon: "🇹🇭" },
  { name: "trinidad", nameKorea: "트리니다드", icon: "🇹🇹" },
  { name: "turkey", nameKorea: "터키", icon: "🇹🇷" },
  { name: "ukraine", nameKorea: "우크라이나", icon: "🇺🇦" },
  { name: "united-arab-emirates", nameKorea: "아랍에미리트", icon: "🇦🇪" },
  { name: "united-kingdom", nameKorea: "영국", icon: "🇬🇧" },
  { name: "united-states", nameKorea: "미국", icon: "🇺🇸" },
  { name: "uruguay", nameKorea: "우루과이", icon: "🇺🇾" },
  { name: "venezuela", nameKorea: "베네수엘라", icon: "🇻🇪" },
  { name: "vietnam", nameKorea: "베트남", icon: "🇻🇳" },
];
